vasa19.BookStore/vasa19.BookStore/Models/BookModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using vasa19.BookStore.Helper;

namespace vasa19.BookStore.Models
{
    public class BookModel
    {
        public string MyField { get; set; }
        public int Id { get; set; }
        [StringLength(100, MinimumLength = 5)]
        [Required(ErrorMessage = "Please enter the title of your book")]
        //[MyCustomValidation]
        public string Title { get; set; }
        [Required(ErrorMessage = "Please enter the author name")]
        public string Author { get; set; }
        [StringLength(300)]
        public string Description { get; set; }
        public string Category { get; set; }
        [Required(ErrorMessage = "Please choose the language of your book")]
        [Display(Name = "Language of book")]
        public int LanguageId { get; set; }
        public string Language { get; set; }
        [Required(ErrorMessage = "Please enter the total pages")]
        [Display(Name = "Total pages of book")]
        public int? TotalPages { get; set; }

        [Display(Name = "Choose the cover photo of your book")]
        [Required]
        public IFormFile CoverPhoto { get; set; }
        public string CoverImageUrl { get; set; }

        [Display(Name = "Choose the gallery images of your book")]
        [Required]
        public IFormFileCollection GalleryFiles { get; set; }
        public List<GalleryModel> Gallery { get; set; }
        [Display(Name = "Upload your book in pdf format")]
        [Required]
        public IFormFile BookPdf { get; set; }
        public string BookPdfUrl { get; set; }
    }
}

vasa19.BookStore/vasa19.BookStore/Models/GalleryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace vasa19.BookStore.Models
{
    public class GalleryModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
    }
}

vasa19.BookStore/vasa19.BookStore/Models/LanguageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace vasa19.BookStore.Models
{
    public class LanguageModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

vasa19.BookStore/vasa19.BookStore/Components/TopBooksViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using vasa19.BookStore.Repository;

namespace vasa19.BookStore.Components
{
    public class TopBooksViewComponent : ViewComponent
    {
        private readonly BookRepository _bookRepository;
        public TopBooksViewComponent(BookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync(int count)
        {
            var books = await _bookRepository.GetTopBooksAsync(count);
            return View(books);
        }
    }
}

vasa19.BookStore/vasa19.BookStore/Controllers/BookController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using vasa19.BookStore.Models;
using vasa19.BookStore.Repository;

namespace vasa19.BookStore.Controllers
{
    public class BookController : Controller
    {
        private readonly BookRepository _bookRepository;
        private readonly LanguageRepository _languageRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BookController(BookRepository bookRepository, LanguageRepository languageRepository, IWebHostEnvironment webHostEnvironment)
        {
            _bookRepository = bookRepository;
            _languageRepository = languageRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<ViewResult> GetAllBooks()
        {
            var data =  await _bookRepository.GetAllBooks();
            return View(data);
        }

        [Route("book-details/{id}", Name = "bookDeatilsRoute")]
        public async Task<ViewResult> GetBook(int id)
        {
            var data =  await _bookRepository.GetBookById(id);
            return View(data);
        }

        public List<BookModel> SearchBooks(string bookName, string authorName)
        {
            return _bookRepository.SearchBook(bookName, authorName);
        }

        public async Task<ViewResult> AddNewBook(bool isSuccess = false, int bookId = 0)
        {
            var model = new BookModel();

            ViewBag.Language = new SelectList(await _languageRepository.GetLanguages(), "Id", "Name");

            ViewBag.IsSuccess = isSuccess;
            ViewBag.BookId = bookId;
            return View(model); 
        }

        [HttpPost]
        public async Task<IActionResult> AddNewBook(BookModel bookModel)
        {
            if(ModelState.IsValid)
            {
                if(bookModel.CoverPhoto != null)
                {
                    string folder = "books/cover/";
                    await UploadImage(folder, bookModel.CoverPhoto);
                }

                if (bookModel.GalleryFiles != null)
                {
                    string folder = "books/gallery/";

                    bookModel.Gallery = new List<GalleryModel>();
                    foreach(var file in bookModel.GalleryFiles)
                    {
                        var gallery = new GalleryModel()
                        {
                            Name = file.FileName,
                            URL = await UploadImage(folder, file)
                        };
                        bookModel.Gallery.Add(gallery);
                    }
                }

                if (bookModel.BookPdf != null)
                {
                    string folder = "books/pdf/";
                    bookModel.BookPdfUrl = await UploadImage(folder, bookModel.BookPdf);
                }

                int id = await _bookRepository.AddNewBook(bookModel);
                if (id > 0)
                {
                    return RedirectToAction("AddNewBook", new { isSuccess = true, bookId = id });
                }
            }
            ViewBag.Language = new SelectList(await _languageRepository.GetLanguages(), "Id", "Name");

            return View();
        }

        private async Task<string> UploadImage(string folderPath, IFormFile file)
        {
            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;
            
            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderPath);

            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

            return "/" + folderPath;
        }
    }
}

vasa19.BookStore/vasa19.BookStore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Dynamic;
using vasa19.BookStore.Models;

namespace vasa19.BookStore.Controllers
{
    public class HomeController : Controller
    {
        [ViewData]
        public string CustomProperty { get; set; }
        [ViewData]
        public string Title { get; set; }
        public ViewResult Index()
        {
            Title = "Home Page";
            CustomProperty = "Custom Value";
            return View();
        }

        public ViewResult AboutUs()
        {
            Title = "About Page";
            return View();
        }

        public ViewResult ContactUs()
        {
            Title = "Contact Page";
            return View();
        }
    }
}

vasa19.BookStore/vasa19.BookStore/Views/Book/AddNewBook.cshtml
@model BookModel
@{ 
    ViewData["Title"] = "Add New Book";
}

<div class="container">
    <h3 class="display-4">Add New Book</h3>
    <hr />
    @if (ViewBag.IsSuccess == true)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Congratulations</strong> You added new book successfully. <br />
            Click <a asp-controller="Book" asp-action="GetBook" asp-route-id="@ViewBag.BookId">here </a>to view the details
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }


<form method="post" enctype="multipart/form-data" asp-action="AddNewBook" asp-controller="Book">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="LanguageId"></label>
        <select asp-for="LanguageId" class="form-control" asp-items="ViewBag.Language">
            <option value="">Please choose the language</option>
        </select>
        <span asp-validation-for="LanguageId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Author"></label>
        <input asp-for="Author" class="form-control" />
        <span asp-validation-for="Author" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="TotalPages"></label>
        <input asp-for="TotalPages" class="form-control" />
        <span asp-validation-for="TotalPages" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="CoverPhoto"></label>
        <div class="custom-file">
            <input asp-for="CoverPhoto" class="custom-file-input" id="customFile" />
            <label class="custom-file-label" for="customFile">Choose File</label>
        </div>
        <span asp-validation-for="CoverPhoto" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="GalleryFiles"></label>
        <div class="custom-file">
            <input asp-for="GalleryFiles" class="custom-file-input" id="customFile" />
            <label class="custom-file-label" for="customFile">Choose File</label>
        </div>
        <span asp-validation-for="GalleryFiles" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="BookPdf"></label>
        <div class="custom-file">
            <input asp-for="BookPdf" class="custom-file-input" id="customFile" />
            <label class="custom-file-label" for="customFile">Choose File</label>
        </div>
        <span asp-validation-for="BookPdf" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Add Book" class="btn btn-primary" />
    </div>
</form>
</div>

vasa19.BookStore/vasa19.BookStore/Views/Book/GetAllBooks.cshtml
@{
    ViewData["Title"] = "All Books";
}
@model IEnumerable<BookModel>


<div class="container">
    <h3 class="display-4">All Books</h3>
    <div class="row">
        @foreach (var book in Model)
        {
            <div class="col-md-4">
                <partial name="_bookThumbnail" model="@book"/>
            </div>
        }
    </div>
</div>

vasa19.BookStore/vasa19.BookStore/Views/Book/GetBook.cshtml
@model BookModel
@{
    ViewData["Title"] = "Book Detail ";
}

<div class="container">
    <h3 class="display-4">Book Details</h3>
    <div class="row">
        <div class="col-md-6">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    @for (int i = 0; i < Model.Gallery.Count(); i++)
                    {
                        <li data-target="#carouselExampleIndicators" data-slide-to="@i" class="@(i==0 ? "active" : "") "></li>
                    }
                </ol>

                <div class="carousel-inner">
                    @for (int i = 0; i < Model.Gallery.Count(); i++)
                    {
                        <div class="@(i==0 ? "carousel-item active" : "carousel-item") ">
                            <img src="@Model.Gallery[i].URL" class="d-block w-100" alt="@Model.Gallery[i].Name">
                        </div>
                    }
                </div>

                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <h1>@Model.Title</h1>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 text-primary">
                    <span class="col-form-label label-primary">By: </span>
                    <span class="monospaced">@Model.Author</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <p class="description">
                        @Model.Description
                    </p>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <button class="btn btn-outline-primary" data-togglr="modal" data-target="#exampleModal">
                        Read Now
                    </button>
                </div>
            </div>

            <hr />

            <ul class="list-group">
                <li class="list-group-item"><span class="font-weight-bold">Category - </span> @Model.Category</li>
                <li class="list-group-item"><span class="font-weight-bold">Total Pages - </span> @Model.TotalPages</li>
                <li class="list-group-item"><span class="font-weight-bold">Language - </span> @Model.Language</li>
            </ul>
        </div>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <iframe src="@Model.BookPdfUrl" class="w-100"></iframe>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <hr />
    <div class="py-5 bg-light">
        <h3 class="h3">Similar Books</h3>
        <div class="row">
            @for (int i = 0; i < 5; i++)
            {
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg">No Thumbnail</svg>
                        <div class="card-body">
                            <h3 class="card-title">book.Title</h3>
                            <p class="card=text">book.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="#" class="btn btn-sm btn-outline-secondary">View Details</a>
                                </div>
                                <small class="text-muted">book.Author</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

vasa19.BookStore/vasa19.BookStore/Views/Home/AboutUs.cshtml
@*@{
    ViewData["Title"] = "About Us";
}*@



<h1 class="h1">About Us</h1>

vasa19.BookStore/vasa19.BookStore/Views/Home/ContactUs.cshtml
@*@{
    ViewData["Title"] = "Contact Us";
}*@



<h1>Contact Us</h1>

vasa19.BookStore/vasa19.BookStore/Views/Home/Index.cshtml
@*@{ 
    ViewData["Title"] = "Home";
}*@

<section class="jumbotron text-center">
    <div class="container">
        <h1>Welcome to Bookstore</h1>

        <p class="lead text-muted">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
        <p>
            <a href="#" class="btn btn-primary my-2">Search Books</a>
        </p>
    </div>
</section>

<div class="py-5 bg-light">
    <div class="container">
        <h3 class="h3">Top Books</h3>
        
        @*@await Component.InvokeAsync("TopBooks")*@ 
        <vc:top-books count="3"></vc:top-books>

       </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            //alert("Document is ready");
        });
    </script>
}

vasa19.BookStore/vasa19.BookStore/Views/Shared/Components/TopBooks/Default.cshtml
@model IEnumerable<BookModel>

<div class="row">
    @foreach (var book in Model)
    {
        <div class="col-md-4">
            <partial name="_bookThumbnail" model="book" />
        </div>
    }

</div>

vasa19.BookStore/vasa19.BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] | Book Store Application</title>

    <environment include="Development">
        <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
        <link href="~/css/Site.css" rel="stylesheet" />
        <link href="~/css/NewStyle.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">

        <link rel="stylesheet"
              href="http://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/twitter-bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              integrity=""
              crossorigin="anonymous">

        <link href="~/css/site.min.css" rel="stylesheet" />
    </environment>
</head>

<body>
   <partial name="_header"/>


    <main role="main">
        @RenderBody()
    </main>

    <partial name="_footer"/>

    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/jquery-validate/jquery.validate.js"></script>
        <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/jquery-validate/jquery.validate.js"></script>
        <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    </environment>

    <script src="~/lib/jquery/jquery.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

    @RenderSection("scripts", required: false)

</body>  
</html>

vasa19.BookStore/vasa19.BookStore/Views/Shared/_bookThumbnail.cshtml
@model BookModel

<div class="card mb-4 shadow-sm">
    <img src="@(string.IsNullOrEmpty(Model.CoverImageUrl) ? "/images/noimage.png" : Model.CoverImageUrl)" class="img-thumbnail" />
    <div class="card-body">
        <h3 class="card-title">@(string.IsNullOrEmpty(Model.Title) ? "Name is not available" : Model.Title)</h3>
        <p class="card-text">@(string.IsNullOrEmpty(Model.Description) ? "Description is not available" : Model.Description)</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a asp-controller="book" asp-action="getbook" asp-route-id="@Model.Id"
                   class="btn btn-sm btn-outline-secondary">View Details</a>
            </div>
            <small class="text-muted">@(string.IsNullOrEmpty(Model.Author) ? "NA" : Model.Author)</small>
        </div>
    </div>
</div>

vasa19.BookStore/vasa19.BookStore/Views/Shared/_footer.cshtml
<footer class="border-top footer text-muted text-center">
    <div class="container">
        Copyright  &copy; Book Store @DateTime.Now.Year
    </div>
</footer>

vasa19.BookStore/vasa19.BookStore/Views/Shared/_header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="~/images/logo.png" width="30" height="30" asp-append-version="true" />
                Book Store
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="btn btn-outline-primary">Login</a>
                        <a class="btn btn-primary">Register</a>
                    </li>
                </ul>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="aboutus">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="contactus">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Book" asp-action="getallbooks">All Books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Book" asp-action="addnewbook">Add Book</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>